/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chatapp;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.LayoutManager;
import java.util.Map;
import java.util.concurrent.ExecutorService;

import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JRadioButton;

import com.listener.ChatMessageSendListener;
import com.listener.UserNameFocussedListener;
import com.util.ClientCommunication;
import com.util.ClientInfo;

/**
 * 
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public NewJFrame(Map<String,ClientCommunication> users,ClientInfo myDetails,ExecutorService threadPoolService) {		
		this.users=users;
		this.myDetails=myDetails;
		this.threadPoolService=threadPoolService;
		initComponents();
	}

	public NewJFrame() {
		// TODO Auto-generated constructor stub
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jInternalFrame1 = new javax.swing.JInternalFrame();
		inputMessage = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		messageArea = new javax.swing.JTextArea();
		userName = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jRadio = new javax.swing.JRadioButton[users.size()];
		
		int counter=0;
		ButtonGroup radioGroup=new ButtonGroup();
		
		for (ClientCommunication clientComm : users.values()) {
			if(myDetails==clientComm.getClientInfo())
				continue;
			jRadio[counter]=new JRadioButton();
			jRadio[counter].setText(clientComm.getClientInfo().getId()+" : "+clientComm.getClientInfo().getName());
			radioGroup.add(jRadio[counter]);
			jRadio[counter++].addItemListener(new UserNameFocussedListener(messageArea));
		}		   
			
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jInternalFrame1.setVisible(true);

		javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(
				jInternalFrame1.getContentPane());
		jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
		jInternalFrame1Layout.setHorizontalGroup(jInternalFrame1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));
		jInternalFrame1Layout.setVerticalGroup(jInternalFrame1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		//inputMessage.setText("inputMessage");
		
		
		ChatMessageSendListener inputMessageListener=new ChatMessageSendListener(messageArea,jRadio,users,myDetails,threadPoolService,messageArea);		
		inputMessage.addKeyListener(inputMessageListener);

		messageArea.setColumns(20);
		messageArea.setRows(5);
		jScrollPane2.setViewportView(messageArea);

		userName.setText("Hello," + myDetails.getName());
		userName.setEditable(false);
		

		
		/*javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);*/
		//jPanel1.setLayout(jPanel1Layout);
		
	/*	SequentialGroup seqGroup=jPanel1Layout
				.createSequentialGroup();
		
		SequentialGroup seqGroup2=jPanel1Layout
		.createSequentialGroup();//.addContainerGap();
*/				
		for (int i = 0; i < jRadio.length; i++) {						
						if (jRadio[i]==null)
						   continue;
						/*seqGroup.addComponent(jRadio[i],
								javax.swing.GroupLayout.DEFAULT_SIZE, 10,
								Short.MAX_VALUE);
						
						
						seqGroup2.addComponent(jRadio[i],
								javax.swing.GroupLayout.DEFAULT_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE);*/
						jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
						jPanel1.add(jRadio[i]);
		}
						
		/*jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(seqGroup));
		
		
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(seqGroup2));
				*/
						
						
		//}
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														277, Short.MAX_VALUE)
												.addComponent(inputMessage)
												.addComponent(userName))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(0, 3, Short.MAX_VALUE)
								.addComponent(userName,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										199,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(inputMessage,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										33,
										javax.swing.GroupLayout.PREFERRED_SIZE))
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	
/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField inputMessage;
	private javax.swing.JInternalFrame jInternalFrame1;
	private javax.swing.JRadioButton jRadio[];
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea messageArea;
	private javax.swing.JTextField userName;
	private Map<String,ClientCommunication> users;
	private ClientInfo myDetails;
	private ExecutorService threadPoolService;
	// End of variables declaration
	
	public Map<String, ClientCommunication> getUsers() {
		return users;
	}

	public void setUsers(Map<String, ClientCommunication> users) {
		this.users = users;
	}
	
	public javax.swing.JTextArea getMessageArea() {
		return messageArea;
	}

	public void setMessageArea(javax.swing.JTextArea messageArea) {
		this.messageArea = messageArea;
	}

	public ExecutorService getThreadPoolService() {
		return threadPoolService;
	}

	public void setThreadPoolService(ExecutorService threadPoolService) {
		this.threadPoolService = threadPoolService;
	}
	
	public javax.swing.JRadioButton[] getjRadio() {
		return jRadio;
	}

	public void setjRadio(javax.swing.JRadioButton[] jRadio) {
		this.jRadio = jRadio;
	}


}
